contexts:
    backend:
        brokers:
            - localhost:9094
    default:
        brokers:
            - localhost:9094
    secured:
        brokers:
            - localhost:19092
    team-a:
        brokers:
            - localhost:19092
    team-b:
        brokers:
            - localhost:29092
    virtual:
        brokers:
            - localhost:19092
current-context: default
